### ISSUE TITLE
What is the swagger url?

### ISSUE THREAD

**Issue by kennyk65** [pjagielski/spring-boot-swagger#3]
This is a nice and convenient library that you've made!  But I have a question:  Assuming you deployed the example you've got posted, what URL would you use to see the swagger generated documentation?

I tried a few paths under http://localhost:8080/api-docs/ but all I saw was raw json.  Does anything special need to be included to generate the GUI output similar to what you see here:https://helloreverb.com/developers/swagger ?

thx,
k

**Comment by pjagielski** [comment]
Hi, sorry for late reply.

Aim for this project is to generate raw Swagger json only. Swagger UI is a separate static html project, yon can grab it from here: https://github.com/swagger-api/swagger-ui. 

So you can have it installed on shared server, aggregating results from various services in one place. No need to install UI on each service/app.

**Comment by kennyk65** [comment]
ok thanks!
